SRC =./sourcefolder/one.c ./sourcefolder/two.c ./sourcefolder/three.c
INC= ./headerfolder

all:
	gcc $(SRC) -I$(INC) -o output

#this will be  executed as:---// gcc one.c two.c three.c file.h -o output //
